### ISSUE TITLE
Abgabe Aufgabe 1.x

### ISSUE THREAD

**Issue by maltems** [faro420/WP-CT#1]
@NerwenElensar @faro420 
Na ihr beiden.
Danke für die Email.
Ne, ich hatte das noch nicht abgegeben. Ich war mir auch nicht sicher, ob das so richtig ist, und dachte ich schaut da einmal drauf...
Aufgabe 1.2 war ja auch noch gar nicht in einer Form, die man hätte abgeben können...
Würde einer von euch beiden das machen? Aufgabe 1.1 könnte man ja so eigentlich abgeben denke ich.
Abgabe war ja eigentlich gestern gewesen...

**Comment by NerwenElensar** [comment]
@maltems @faro420 
Sorry lag das Wochenende mit Migräne flach, ich hab jetzt Aufgabe 1.2 in Form gegossen. Ich finde deine Aufgabe 1.1 nicht im Github oder bin vielleicht nur blind. Schaut mal drüber und dann schick das ab. Da ich Aufgabe 1.1 nicht finden kann müsste das vielleicht @maltems machen.

**Comment by maltems** [comment]
Erledigt, habe Buth wie ihr seht ne Mail geschickt.
Jo, ich hatte Aufgabe 1.1 nicht im PDF-Format in den Ordner getan... war nicht so schlau von mir. Danke für Aufgabe 1.2 @NerwenElensar
